name: Build Web

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:
    inputs:
      COMMIT_ID:
        required: true
        type: string

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for push to complete
        if: github.event_name == 'workflow_call'
        run: |
          echo "Input: ${{ inputs.COMMIT_ID }}"
          echo "Clone: $(git show --format='%H' --no-patch)"
          while [ ${{ inputs.COMMIT_ID }} != $(git show --format='%H' --no-patch) ]; do
            sleep 1
            git pull
            echo "Input: ${{ inputs.COMMIT_ID }}"
            echo "Clone: $(git show --format='%H' --no-patch)"
          done

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Build
        run: |
          flutter --version
          flutter pub get
          flutter build web --web-renderer html --base-href /$(echo ${{ github.repository }} | sed -e "s#.*/##")/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
